version: '3'
services:
  web:
    build:
      context: . #Dockerfile location
      dockerfile: Dockerfile.dev #file name
    ports:
      - 3300:3000
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm", "run", "test" ]
